"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import struct
from io import BytesIO


class performance_status_lcm_t:
    __slots__ = ["heart_beat", "dance_id", "is_finished"]

    __typenames__ = ["boolean", "int32_t", "boolean"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.heart_beat = False
        """ LCM Type: boolean """
        self.dance_id = 0
        """
        True for valid message, False for heart beat signal
        LCM Type: int32_t
        """

        self.is_finished = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(performance_status_lcm_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bib", self.heart_beat, self.dance_id, self.is_finished))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, "read"):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != performance_status_lcm_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return performance_status_lcm_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = performance_status_lcm_t()
        self.heart_beat = bool(struct.unpack("b", buf.read(1))[0])
        self.dance_id = struct.unpack(">i", buf.read(4))[0]
        self.is_finished = bool(struct.unpack("b", buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if performance_status_lcm_t in parents:
            return 0
        tmphash = (0x59CD486A6C70BA4D) & 0xFFFFFFFFFFFFFFFF
        tmphash = (((tmphash << 1) & 0xFFFFFFFFFFFFFFFF) + (tmphash >> 63)) & 0xFFFFFFFFFFFFFFFF
        return tmphash

    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if performance_status_lcm_t._packed_fingerprint is None:
            performance_status_lcm_t._packed_fingerprint = struct.pack(
                ">Q", performance_status_lcm_t._get_hash_recursive([])
            )
        return performance_status_lcm_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", performance_status_lcm_t._get_packed_fingerprint())[0]
